---
title: An R Markdown document converted from "AED_R.ipynb"
output: html_document
---

# Kelompok 5
## beranggotakan

1.   Rizal Mujahiddan (G64190069)
2.   Nisma Karmiahtun F (G64190036)
3.   Dhiya Ulayya Tsabitah (G1401201013)
4.   Muhammad Nachnoer Novatron Fitra Arss (G1401201014)


Install package

```{r}
install.packages("qqplotr")
```

## Download filenya

```{r}
url <- "https://docs.google.com/uc?id=1ebsw2GaAK9HdyrGyzCCYb7s7eyQ4-fJM&export=downloads"
download.file(url,"Data untuk Eksplorasi.xlsx")
```

##Dilakukanlah uji formal

```{r}
library(readxl)
Datasheet1 <- read_excel("Data untuk Eksplorasi.xlsx", skip = 1)
View(Datasheet1)
Datasheet3 <- read_excel("Data untuk Eksplorasi.xlsx", sheet = 3, skip = 2)
colnames(Datasheet3)[2]<-c("Country") 
DataGabungan <- merge(Datasheet3, Datasheet1, by = "Country")
DataFix <- DataGabungan[,c(-3:-5,-8:-11)]

var1<- na.omit(DataFix$`Real GDP growth ( avg last 5yrs%)`)
var2<- na.omit(DataFix$`Loan-deposit ratio (%)`)
```

```{r}
#kolmogorof-smirnov test
#normal
set.seed(42); ks.test(var1, "pnorm", mean(var1), sd(var1))
```

```{r}
#log normal
set.seed(42); ks.test(var1, "plnorm", mean(log(var1)), sd(log(var1)))
```

```{r}
#chi-squares
set.seed(42); ks.test(var1, "pchisq", mean(var1))
```

```{r}
#eksponential
set.seed(42); ks.test(log(var1), "pexp", 1/mean(var1))
```

##plot histogram

```{r}
library(ggplot2)
sheet1 <- read_excel("Data untuk Eksplorasi.xlsx", skip = 1)
sheet3 <- read_excel("Data untuk Eksplorasi.xlsx", sheet="country code", skip=2)
colnames(sheet3)[2] <- c("Country")
sheet_gab <- merge(sheet1, sheet3, by = "Country");
ggplot(sheet_gab, aes(x=`Real GDP growth ( avg last 5yrs%)`,fill=`region`)) + 
  geom_histogram(binwidth = 2, color="darkblue") + facet_wrap(~`region`)+
  geom_vline(aes(xintercept=mean(`Real GDP growth ( avg last 5yrs%)`)), color="black",
             linetype="dashed", size=0.5)
```

```{r}
ggplot(sheet_gab, aes(x=`Loan-deposit ratio (% avg 5yr)`,fill=`region`)) + 
  geom_histogram(binwidth = 8, color="darkblue") + facet_wrap(~`region`)+
  geom_vline(aes(xintercept=mean(`Loan-deposit ratio (% avg 5yr)`)), color="black",
             linetype="dashed", size=0.5)
```

## plot qqplot

```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(qqplotr)

metadata <- read_xlsx("Data untuk Eksplorasi.xlsx",
                      sheet="penjelasan peubah",range="B2:F38",col_names=FALSE)
colnames(metadata) <- c("var","nama","arti","sistem","sumber data")

Sheet1 <- read_excel("Data untuk Eksplorasi.xlsx", skip=1)
Sheet3 <- read_excel("Data untuk Eksplorasi.xlsx", 
                     sheet="country code", skip=2)


colnames(Sheet3)[2]<-c("Country");Sheet3
Sheet13 <- merge(Sheet3, Sheet1, by="Country");Sh13<-Sheet13[,c(-3:-5,-8:-11)]

s13<- Sh13%>%filter(region=="Asia")
S13 <- Sh13%>%arrange(region,`sub-region`);S13
p<-as.factor(S13$`sub-region`);p
S13$HDI <- as.numeric(S13$HDI)
S13$`sub-region`<-factor(p, levels=c("Central Asia", "Eastern Asia", "Southern Asia",
                                     "South-eastern Asia", "Western Asia",
                                     "Northern Africa", "Sub-Saharan Africa",
                                     "Eastern Europe","Northern Europe","Southern Europe",
                                     "Western Europe","Latin America and the Caribbean", 
                                     "Northern America", "Australia and New Zealand"))
```

```{r}
ggplot(S13, aes(sample = `Loan-deposit ratio (% avg 5yr)`)) + 
  stat_qq_point()+stat_qq_line(col="red")+
  labs(x="theorectical",y="Sample",
       title = "QQplot Loan-deposit ratio (% avg 5yr) in Gaussian Distribtion")
```

```{r}
ggplot(S13, aes(sample = `Loan-deposit ratio (% avg 5yr)`)) + 
  stat_qq_point(distribution="lnorm")+  
  stat_qq_line(col="red",distribution = "lnorm")+
  labs(x="theorectical",y="Sample",
       title = "QQplot Loan-deposit ratio (% avg 5yr) in lognormal Distribtion")
```

```{r}
ggplot(S13, aes(sample = `Loan-deposit ratio (% avg 5yr)`)) + 
  stat_qq_point(distribution="chisq")+  
  stat_qq_line(col="red",distribution = "chisq")+
  labs(x="theorectical",y="Sample", 
       title = "QQplot Loan-deposit ratio (% avg 5yr) in Chisquare Distribtion")
```

```{r}
ggplot(S13, aes(sample = `Loan-deposit ratio (% avg 5yr)`)) + 
  stat_qq_point(distribution="exp")+
  stat_qq_line(col="red",distribution="exp")+
  labs(x="theorectical",y="Sample",
       title = "QQplot Loan-deposit ratio (% avg 5yr) in exponensial Distribtion")
```



```{r}
ggplot(S13, aes(sample = `Real GDP growth ( avg last 5yrs%)`)) + 
  stat_qq_point()+stat_qq_line(col="red")+
  labs(x="theorectical",y="Sample",
       title = "QQplot Real GDP growth ( avg last 5yrs%) in Gaussian Distribtion")
```

```{r}
ggplot(S13, aes(sample = `Real GDP growth ( avg last 5yrs%)`)) + 
  stat_qq_point(distribution = "chisq",
                dparams = list(df = mean(S13$`Real GDP growth ( avg last 5yrs%)`)))+
  stat_qq_line(distribution = "chisq",col="red",
               dparams = list(df = mean(S13$`Real GDP growth ( avg last 5yrs%)`)))+
  labs(x="theorectical",y="Sample",
       title = "QQplot Real GDP growth ( avg last 5yrs%) in Chisquare Distribtion")
```

```{r}
ggplot(S13, aes(sample = `Real GDP growth ( avg last 5yrs%)`)) + 
  stat_qq_point(distribution="lnorm",
                dparams=list(meanlog=mean(log(S13$`Real GDP growth ( avg last 5yrs%)`)),
                             sdlog = sd(log(S13$`Real GDP growth ( avg last 5yrs%)`))))+  
  labs(x="theorectical",y="Sample",
       title = "QQplot Real GDP growth ( avg last 5yrs%) in lognormal Distribtion")
```

```{r}
ggplot(S13, aes(sample = `Real GDP growth ( avg last 5yrs%)`)) + 
  stat_qq_point(distribution="exp",
                dparams=list(rate=1/mean(S13$`Real GDP growth ( avg last 5yrs%)`)))+  
  stat_qq_line(col="red",distribution = "exp",
               dparams = list(rate=1/mean(S13$`Real GDP growth ( avg last 5yrs%)`)))+
  labs(x="theorectical",y="Sample",
       title = "QQplot Real GDP growth ( avg last 5yrs%) in exponential Distribtion")
```

```{r}
ggplot(S13, aes(sample = `Loan-deposit ratio (% avg 5yr)`)) + 
  stat_qq_point() + stat_qq_line(col="red") + 
  facet_wrap(~`region`)+
  labs(title = "QQplot Loan-deposit ratio (% avg 5yr) by region")
```

```{r}
ggplot(S13, aes(sample = `Real GDP growth ( avg last 5yrs%)`)) + 
  stat_qq_point() + stat_qq_line(col="red") + 
  facet_wrap(~`region`)+
  labs(title = "QQplot Real GDP growth ( avg last 5yrs%) by region")
```

## plot boxplot

```{r}
ggplot(S13, mapping=aes(x=`Real GDP growth ( avg last 5yrs%)`, y=region))+
  geom_boxplot(alpha=0.7, fill=c("#03d3f2", "#ffcd88", "#ff8fb4","#fffe98","#06d8ae"),
  outlier.fill = "#fd7576", outlier.size=1.96, outlier.alpha=0.5, shape=8)+ 
  labs(title="Sebaran Pertumbuhan PDB Riil Antar Benua",subtitle="Dalam 5 Tahun Terakhir", 
        x="Pertumbuhan PDB Riil(%)", y="Benua")+
  theme_bw()+coord_flip()+stat_summary(fun="mean")
```

```{r}
ggplot(S13, mapping=aes(x=`Loan-deposit ratio (% avg 5yr)`, y=region))+
geom_boxplot(alpha=0.7, fill=c("#03d3f2", "#ffcd88", "#ff8fb4","#fffe98","#06d8ae"),
outlier.fill = "#fd7576", outlier.size=1.96, outlier.alpha=0.5, shape=8)+ 
  labs(title="Sebaran Rataan Loan-Deposit Ratio (LDR) Antar Benua", 
  subtitle="Dalam 5 Tahun Terakhir", x="LDR(%)", y="Benua")+
  theme_bw()+coord_flip()+stat_summary(fun="mean")
```

